export default {
  API_HOST: process.env.REACT_APP_MAILER_API_HOST,
  API_PORT: process.env.REACT_APP_MAILER_PORT,
  GITHUB_TOKEN: process.env.REACT_APP_GITHUB_API_TOKEN,
  GITHUB_USER: process.env.REACT_APP_GITHUB_USER
}